### ISSUE TITLE
Bootstrap button bar dropdowns not working.

### ISSUE THREAD

**Issue by nickratering** [concrete5/migration_tool#5]
Bootstrap button bar dropdowns not working.

/packages/migration_tool/single_pages/dashboard/system/migration/view_batch.php
Around lines 14-60 should be something like:

`            <div class="btn-group" role="group" aria-label="Batch options">
                <a href="javascript:void(0)" data-dialog="add-to-batch" data-dialog-title="<?= t('Add Content') ?>"
                   class="btn btn-sm btn-light"><?= t("Add Content to Batch") ?></a>
                <a href="<?= $view->action('batch_files', $batch->getID()) ?>" class="btn btn-sm btn-light"><?= t('Files') ?></a>
                
                <div class="dropdown">
                    <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        <?= t('Edit') ?>
                    </button>

                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <a class="dropdown-item" href="<?= $view->action('map_content', $batch->getId())?>"><?=t('Map Content')?></a>
                        <div class="dropdown-divider"></div>
                        <div class="dropdown-header"><?= t('Settings') ?></div>
                        <a class="dropdown-item" href="<?=URL::to('/dashboard/system/migration/import/settings/basics', $batch->getID())?>" class=""><?= t("Basics") ?></a>
                            <?php foreach($settings as $setting) { ?>
                        <a class="dropdown-item" href="<?=URL::to($setting, $batch->getID())?>" class=""><?= t($setting->getCollectionName())?></a>
                            <?php } ?>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="javascript:void(0)" data-dialog="clear-batch-mappings"
                               data-dialog-title="<?= t('Clear Batch Mappings') ?>" class=""><?= t("Clear Batch Mappings") ?></a>
                        <a class="dropdown-item" href="javascript:void(0)" data-action="rescan-batch"
                               data-dialog-title="<?= t('Rescan Batch') ?>" class=""><?= t("Rescan Batch") ?></a>
                    </div>
                </div>
                <div class="dropdown">
                    <button type="button" id="dropdownMenuButton2" class="btn btn-sm btn-danger dropdown-toggle" data-bs-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                        <?= t('Delete') ?>
                        <span class="caret"></span>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
                        <a class="disabled dropdown-item" href="javascript:void(0)" data-dialog="delete-batch-items"
                                                data-dialog-title="<?= t('Delete Selected') ?>"><?= t("Delete Selected") ?></a>
                        <div class="dropdown-divider"></div>
                        <a href="javascript:void(0)" class="dropdown-item" data-dialog="clear-batch"
                               data-dialog-title="<?= t('Clear Batch') ?>" class=""><?= t("Clear Batch") ?></a>
                        <a class="dropdown-item" href="javascript:void(0)" data-dialog="delete-batch"
                               data-dialog-title="<?= t('Delete Batch') ?>"><?= t("Delete Batch") ?></a>
                    </div>
                </div>

                <a href="javascript:void(0)" class="btn btn-sm btn-primary" data-dialog="create-content"
                   data-dialog-title="<?= t('Import Batch to Site') ?>" class=""><?= t("Import Batch to Site") ?></a>

            </div>
`
Result:
![Screenshot 2021-11-17 at 11 49 47](https://user-images.githubusercontent.com/3337142/142186957-80b2bca8-a548-4c13-b6d2-14b4aa1745ae.png)

**Comment by drbiskit** [comment]
In addition to this, if you force the drop down to appear, and then go to 'Map Content' - the page is not working correctly. The page appears initially with some correct mappings in place, but when it finishes loading they are all stripped out, appearing as per the grabs below.

![Screen Shot 2021-11-16 at 17 09 08](https://user-images.githubusercontent.com/4929240/142190222-7452315f-0db7-420f-9541-b62aa7c9440f.png)

![Screen Shot 2021-11-16 at 17 09 13](https://user-images.githubusercontent.com/4929240/142190201-7f18c0a2-8c10-40b3-9be8-c0cb19361209.png)

**Comment by nickratering** [comment]
@drbiskit Yes, I've the same issue, but this should be posted in another issue. I asked the community if this has something to to with legacy compatibility: https://concrete5.slack.com/archives/C2N3FLUBW/p1637145981050100

**Comment by aembler** [comment]
Thanks - I've added the `data-bs-toggle`
