### ISSUE TITLE
Mapping is not working in V9 (At least when importing from legacy 5.6 migration tool export)

### ISSUE THREAD

**Issue by nickratering** [concrete5/migration_tool#6]
Based on question in Slack: https://concrete5.slack.com/archives/C2N3FLUBW/p1637145981050100

Also noticed by @drbiskit:

In addition to this, if you force the drop down to appear, and then go to 'Map Content' - the page is not working correctly. The page appears initially with some correct mappings in place, but when it finishes loading they are all stripped out, appearing as per the grabs below.

![Screen Shot 2021-11-16 at 17 09 08](https://user-images.githubusercontent.com/4929240/142190222-7452315f-0db7-420f-9541-b62aa7c9440f.png)

![Screen Shot 2021-11-16 at 17 09 13](https://user-images.githubusercontent.com/4929240/142190201-7f18c0a2-8c10-40b3-9be8-c0cb19361209.png)

_Originally posted by @drbiskit in https://github.com/concrete5/migration_tool/issues/5#issuecomment-971476523_

**Comment by aembler** [comment]
Thanks – This is a bug in the bootstrap select library when use with optgroups. In the meantime I've just removed Bootstrap Select from these select menus.
